// <auto-generated />
using BlazorMoviesApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorMoviesApp.Migrations
{
    [DbContext(typeof(MovieReviewDBContext))]
    [Migration("20231208042437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorMoviesApp.Components.Models.MovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet.",
                            ImageUrl = "/images/movies/Highlander.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet. Aenean in pellentesque erat, at pretium nulla. Ut dui sem, viverra in porta vel, molestie nec mi.",
                            Title = "Highlander"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet.",
                            ImageUrl = "/images/movies/Godfather.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet. Aenean in pellentesque erat, at pretium nulla. Ut dui sem, viverra in porta vel, molestie nec mi.",
                            Title = "Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet.",
                            ImageUrl = "/images/movies/LastOfTheMohicans.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet. Aenean in pellentesque erat, at pretium nulla. Ut dui sem, viverra in porta vel, molestie nec mi.",
                            Title = "Last of the Mohicans"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet.",
                            ImageUrl = "/images/movies/RearWindow.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet. Aenean in pellentesque erat, at pretium nulla. Ut dui sem, viverra in porta vel, molestie nec mi.",
                            Title = "Rear Window"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet.",
                            ImageUrl = "/images/movies/RoadHouse.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet. Aenean in pellentesque erat, at pretium nulla. Ut dui sem, viverra in porta vel, molestie nec mi.",
                            Title = "Road House"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet.",
                            ImageUrl = "/images/movies/StarTreck4.png",
                            Review = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tellus vel orci gravida imperdiet. Aenean in pellentesque erat, at pretium nulla. Ut dui sem, viverra in porta vel, molestie nec mi.",
                            Title = "Star Treck IV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
